[package]
name = "common-defs"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { version = ">=0.11", optional=true }
bytemuck = { version = "1.12", features = ["derive"] }

[lib]
path = "src/lib.rs"
